### ISSUE TITLE
Markdown merge utility

### ISSUE THREAD

**Issue by donmendelson** [FIXTradingCommunity/md-grammar#8]
Use the file import facility (issue #7) to merge external file snippets and write the resulting markdown document. The infostring and importspec of a fenced code block are retained in the output so a file can be refreshed from external sources as often as desired. The big idea is to create living documents using technical resources that are managed and validated elsewhere.

**Comment by kleihan** [comment]
That will be a great feature, providing more flexibility and accuracy/correctness. The source location of the snippets should be included in the versioning/tagging logic, so that we can always say which version of the snippet was included with which version of a specification.
